PaintingGroupWebApp/ViewModels/DashboardViewModel.cs
using PaintingGroupWebApp.Models;
using PaintingGroupWebApp.Models;
namespace PaintingGroupWebApp.ViewModels
{
    public class DashboardViewModel
    {
        public List<Meeting> Meetings { get; set; }
        public List<Club> Clubs { get; set; }
    }
}

PaintingGroupWebApp/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PaintingGroupWebApp.Data;
using PaintingGroupWebApp.Interfaces;
using PaintingGroupWebApp.Models;
using PaintingGroupWebApp.ViewModels;

namespace PaintingGroupWebApp.Controllers
{
    public class ClubController : Controller
    {
        private readonly IClubRepository _clubRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ClubController(IClubRepository clubRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _clubRepository = clubRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Club> clubs = await _clubRepository.GetAll();
            return View(clubs);
        }
        public async Task<IActionResult> Detail(int id) 
        {
            Club club = await _clubRepository.GetByIdAsync(id);
            return View(club);
        }
        public IActionResult Create() 
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createClubViewModel = new CreateClubViewModel { AppUserId = curUserId };
            return View(createClubViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateClubViewModel clubVM)
        {
            if(ModelState.IsValid) 
            {
                var result = await _photoService.AddPhotoAsync(clubVM.Image);
                var club = new Club
                {
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = result.Url.ToString(),
                    AppUserId = clubVM.AppUserId,
                    Address = new Address
                    {
                        Street = clubVM.Address.Street,
                        City = clubVM.Address.City,
                        County= clubVM.Address.County,
                    },
                    ClubCategory = clubVM.ClubCategory
                };
                _clubRepository.Add(club);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }
            return View(clubVM);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var club = await _clubRepository.GetByIdAsync(id);
            if (club == null) return View("Error");
            var clubVM = new EditClubViewModel
            {
                Title = club.Title,
                Description = club.Description,
                AddressId = club.AddressId,
                Address = club.Address,
                URL = club.Image,
                ClubCategory = club.ClubCategory
            };
            return View(clubVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditClubViewModel clubVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit club");
                return View("Edit", clubVM);
            }

            var userClub = await _clubRepository.GetByIdAsyncNoTracking(id);

            if (userClub != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(userClub.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(clubVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(clubVM.Image);

                var club = new Club
                {
                    Id = id,
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = photoResult.Url.ToString(),
                    AddressId = clubVM.AddressId,
                    Address = clubVM.Address,
                    ClubCategory = clubVM.ClubCategory
                };

                _clubRepository.Update(club);

                return RedirectToAction("Index");
            }
            else
            {
                return View(clubVM);
            }


        }

        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            return View(clubDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteClub(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");

            _clubRepository.Delete(clubDetails);
            return RedirectToAction("Index");
        }

    }
}

PaintingGroupWebApp/Controllers/DashboardController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using PaintingGroupWebApp.Data;
using PaintingGroupWebApp.Interfaces;
using PaintingGroupWebApp.Models;
using PaintingGroupWebApp.ViewModels;

namespace PaintingGroupWebApp.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRespository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IPhotoService _photoService;

        public DashboardController(IDashboardRepository dashboardRespository, IHttpContextAccessor httpContextAccessor, IPhotoService photoService)
        {
            _dashboardRespository = dashboardRespository;
            _httpContextAccessor = httpContextAccessor;
            _photoService = photoService;
        }
        private void MapUserEdit(AppUser user, EditUserDashboardViewModel editVM, ImageUploadResult photoResult)
        {
            user.Id = editVM.Id;
            user.FavouriteStyle = editVM.FavouriteStyle;
            user.FavouriteMedium = editVM.FavouriteMedium;
            user.ProfileImageUrl = photoResult.Url.ToString();
            user.City = editVM.City;
            user.County = editVM.County;
        }
        public async Task<IActionResult> Index()
        {
            var userRaces = await _dashboardRespository.GetAllUserMeetings();
            var userClubs = await _dashboardRespository.GetAllUserClubs();
            var dashboardViewModel = new DashboardViewModel()
            {
                Meetings = userRaces,
                Clubs = userClubs
            };
            return View(dashboardViewModel);
        }
        public async Task<IActionResult> EditUserProfile()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var user = await _dashboardRespository.GetUserById(curUserId);
            if (user == null) return View("Error");
            var editUserViewModel = new EditUserDashboardViewModel()
            {
                Id = curUserId,
                FavouriteStyle = user.FavouriteStyle,
                FavouriteMedium = user.FavouriteMedium,
                ProfileImageUrl = user.ProfileImageUrl,
                City = user.City,
                County = user.County
            };
            return View(editUserViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditUserProfile(EditUserDashboardViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("EditUserProfile", editVM);
            }

            AppUser user = await _dashboardRespository.GetByIdNoTracking(editVM.Id);

            if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null)
            {

                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _dashboardRespository.Update(user);

                return RedirectToAction("Index");
            }
            else
            {
                try
                {
                    await _photoService.DeletePhotoAsync(user.ProfileImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(editVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _dashboardRespository.Update(user);

                return RedirectToAction("Index");
            }
        }
    }
}

PaintingGroupWebApp/Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PaintingGroupWebApp.Data;
using PaintingGroupWebApp.Data.Enum;
using PaintingGroupWebApp.Interfaces;
using PaintingGroupWebApp.Models;
using PaintingGroupWebApp.Repository;
using PaintingGroupWebApp.Services;
using PaintingGroupWebApp.ViewModels;

namespace PaintingGroupWebApp.Controllers
{
    public class MeetingController : Controller
    {
        private readonly IMeetingRepository _meetingRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public MeetingController(IMeetingRepository meetingRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _meetingRepository = meetingRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Meeting> meetings = await _meetingRepository.GetAll();
            return View(meetings);
        }
        public async Task<IActionResult> Detail(int id)
        {
            Meeting meeting = await _meetingRepository.GetByIdAsync(id); 
            return View(meeting);
        }
        public IActionResult Create()
        {
            var curUserID = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createMeetingViewModel = new CreateMeetingViewModel { AppUserId = curUserID };
            return View(createMeetingViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateMeetingViewModel meetingVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(meetingVM.Image);
                var meeting = new Meeting
                {
                    Title = meetingVM.Title,
                    Description = meetingVM.Description,
                    Image = result.Url.ToString(),
                    AppUserId = meetingVM.AppUserId,
                    Address = new Address
                    {
                        Street = meetingVM.Address.Street,
                        City = meetingVM.Address.City,
                        County = meetingVM.Address.County,
                    },
                    MeetingCategory = meetingVM.MeetingCategory
                };
                _meetingRepository.Add(meeting);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }
            return View(meetingVM);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var meeting = await _meetingRepository.GetByIdAsync(id);
            if (meeting == null) return View("Error");
            var clubVM = new EditMeetingViewModel
            {
                Title = meeting.Title,
                Description = meeting.Description,
                AddressId = meeting.AddressId,
                Address = meeting.Address,
                URL = meeting.Image,
                MeetingCategory = meeting.MeetingCategory
            };
            return View(clubVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditMeetingViewModel meetingVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit club");
                return View("Edit", meetingVM);
            }

            var userRace = await _meetingRepository.GetByIdAsyncNoTracking(id);

            if (userRace != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(userRace.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(meetingVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(meetingVM.Image);


                var race = new Meeting
                {
                    Id = id,
                    Title = meetingVM.Title,
                    Description = meetingVM.Description,
                    Image = photoResult.Url.ToString(),
                    AddressId = meetingVM.AddressId,
                    Address = meetingVM.Address,
                    MeetingCategory = meetingVM.MeetingCategory
                };

                _meetingRepository.Update(race);

                return RedirectToAction("Index");
            }
            else
            {
                return View(meetingVM);
            }


        }
        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _meetingRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            return View(clubDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteClub(int id)
        {
            var raceDetails = await _meetingRepository.GetByIdAsync(id);
            if (raceDetails == null) return View("Error");

            _meetingRepository.Delete(raceDetails);
            return RedirectToAction("Index");
        }
    }
}

PaintingGroupWebApp/Views/Dashboard/EditUserProfile.cshtml
@using PaintingGroupWebApp.ViewModels
@model EditUserDashboardViewModel


<form method="post" asp-action="EditUserProfile" enctype="multipart/form-data">
    <input type="hidden" id="Id" name="Id" asp-for="Id" />
    <div class="form-group">
        <label asp-for="FavouriteStyle">FavouriteStyle</label>
        <input asp-for="FavouriteStyle" class="form-control" placeholder="FavouriteStyle">
        <span asp-validation-for="FavouriteStyle" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FavouriteMedium">FavouriteMedium</label>
        <input asp-for="FavouriteMedium" class="form-control" placeholder="FavouriteMedium">
        <span asp-validation-for="FavouriteMedium" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="City">City</label>
        <input asp-for="City" class="form-control" placeholder="City">
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="County">County</label>
        <input asp-for="County" class="form-control" placeholder="County">
        <span asp-validation-for="County" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Profile Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

PaintingGroupWebApp/Views/Dashboard/Index.cshtml
@model PaintingGroupWebApp.ViewModels.DashboardViewModel

<h1 class="display-4 fw-normal">User Dashboard</h1>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Club" asp-action="Create">Create Club</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Meeting" asp-action="Create">Create Race</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Dashboard" asp-action="EditUserProfile">Edit User Profile</a>
<div class="album py-5 bg-light">
    <div class="container">
        <h2 class="display-4 fw-normal">Your races</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            @foreach (var item in Model.Meetings)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a asp-controller="Meeting" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Meeting" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.MeetingCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
        <h2 class="display-4 fw-normal">Your Clubs</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Clubs)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id"
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a asp-controller="Club" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Club" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.ClubCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>